@startuml


package model {

	abstract Stack
	Stack <|-- Deck
	Stack <|-- Discarded
	Stack <|-- Work
	Stack <|-- Target
	Card -o Stack
	Game *-up- "1" Deck
	Game *-up- "1" Discarded
	Game *-up- "7" Work
	Game *-up- "4" Target

}

@enduml