@startuml
' TODO: Rellenar las condiciones
start
:repartir;
while (no completo ni bloqueado?)
	split
	if (cartas en mazo?) then
		:sacar a descarte;
	endif
	split again
	if (no hay cartas en mazo?) then
		:mover pila de descarte entera a mazo;
	endif
	split again
	if (carta en descarte compatible**[1]** con carta visible en trabajo) then
		:mover de descarte a trabajo;
	endif
	split again
	if (carta en descarte compatible**[2]** con carta visible en objetivo) then
		:mover de descarte a objetivo;
	endif
	split again
	if (cartas visibles en trabajo1 compatible**[1]** con cartas visibles en trabajo 2) then
		:mover entre trabajos;
	endif
	split again
	if (cima de trabajo compatible**[2]** con objetivo) then
		:mover de trabajo a objetivo;
	endif
	split again
	if (cima de objetivo compatible**[1]** con trabajo) then
		:mover de objetivo a trabajo;
	endif
	endsplit
endwhile
stop
	
@enduml